// generated by AheadLibEx (Rust) - only x86
// Author: i1tao
// Blog: https://www.winsec.cn
// Github: https://github.com/i1tao/AheadLibEx

#include <array>
#include <windows.h>
#include <strsafe.h>

#include "{{PATCH_HEADER}}"

{{EXPORT_PRAGMAS}}

extern "C" {
{{FORWARD_DECLS}}
}

{{X86_TRAMPOLINES}}

namespace aheadlibex {

using ForwarderAddress = FARPROC;
using PathBuffer = std::array<TCHAR, MAX_PATH>;
using MessageBuffer = std::array<TCHAR, MAX_PATH * 2>;
using OrdinalBuffer = std::array<char, 64>;

constexpr TCHAR kMessageCaption[] = TEXT("AheadLibEx");

HMODULE g_origin_module_handle = nullptr;
HMODULE g_proxy_module_handle = nullptr;
HANDLE g_patch_stop_event = nullptr;
bool g_user_patch_started = false;

HMODULE proxy_module() noexcept
{
    return g_proxy_module_handle;
}

HMODULE original_module() noexcept
{
    return g_origin_module_handle;
}

HANDLE stop_event() noexcept
{
    return g_patch_stop_event;
}

bool stop_requested() noexcept
{
    return g_patch_stop_event != nullptr
        && ::WaitForSingleObject(g_patch_stop_event, 0) == WAIT_OBJECT_0;
}

void show_message_box(const TCHAR* message, UINT flags = MB_ICONSTOP) noexcept
{
    ::MessageBox(nullptr, message, kMessageCaption, flags);
}

void show_last_error(const TCHAR* prefix, const TCHAR* detail = nullptr) noexcept
{
    MessageBuffer message{};
    if (detail != nullptr && detail[0] != TEXT('\0'))
    {
        ::StringCchPrintf(
            message.data(),
            message.size(),
            TEXT("%s %s, AheadLibEx cannot continue.\nerror code:0x%08X"),
            prefix,
            detail,
            ::GetLastError());
    }
    else
    {
        ::StringCchPrintf(
            message.data(),
            message.size(),
            TEXT("%s, AheadLibEx cannot continue.\nerror code:0x%08X"),
            prefix,
            ::GetLastError());
    }
    show_message_box(message.data());
}

void show_path_too_long() noexcept
{
    show_message_box(TEXT("Resolved original DLL path is too long, AheadLibEx cannot continue."));
}

bool copy_text(PathBuffer& target, const TCHAR* text) noexcept
{
    return SUCCEEDED(::StringCchCopy(target.data(), target.size(), text));
}

bool append_text(PathBuffer& target, const TCHAR* text) noexcept
{
    return SUCCEEDED(::StringCchCat(target.data(), target.size(), text));
}

bool query_module_directory(HMODULE module, PathBuffer& path) noexcept
{
    const auto length = ::GetModuleFileName(module, path.data(), static_cast<DWORD>(path.size()));
    if (length == 0 || length >= path.size())
    {
        show_last_error(TEXT("GetModuleFileName failed"));
        return false;
    }

    size_t last_separator = static_cast<size_t>(-1);
    for (size_t index = 0; path[index] != TEXT('\0'); ++index)
    {
        if (path[index] == TEXT('\\') || path[index] == TEXT('/'))
        {
            last_separator = index;
        }
    }

    if (last_separator == static_cast<size_t>(-1))
    {
        path[0] = TEXT('\0');
    }
    else
    {
        path[last_separator + 1] = TEXT('\0');
    }

    return true;
}

bool query_system_dll_path(PathBuffer& path, const TCHAR* dll_name) noexcept
{
    const auto length = ::GetSystemDirectory(path.data(), static_cast<UINT>(path.size()));
    if (length == 0 || length >= path.size())
    {
        show_last_error(TEXT("GetSystemDirectory failed"));
        return false;
    }

    if (!append_text(path, TEXT("\\")) || !append_text(path, dll_name))
    {
        show_path_too_long();
        return false;
    }

    return true;
}

bool is_absolute_path(const TCHAR* path) noexcept
{
    return (path[0] != TEXT('\0') && path[1] == TEXT(':'))
        || path[0] == TEXT('\\')
        || path[0] == TEXT('/');
}

bool load_original_module_from_path(const PathBuffer& module_path) noexcept
{
    g_origin_module_handle = ::LoadLibrary(module_path.data());
    if (g_origin_module_handle == nullptr)
    {
        show_last_error(TEXT("Cannot locate"), module_path.data());
        return false;
    }

    return true;
}

void free_origin_module() noexcept
{
    if (g_origin_module_handle != nullptr)
    {
        ::FreeLibrary(g_origin_module_handle);
        g_origin_module_handle = nullptr;
    }
}

bool create_patch_stop_event() noexcept
{
    g_patch_stop_event = ::CreateEvent(nullptr, TRUE, FALSE, nullptr);
    if (g_patch_stop_event == nullptr)
    {
        show_last_error(TEXT("CreateEvent failed"));
        return false;
    }

    return true;
}

void signal_patch_stop() noexcept
{
    if (g_patch_stop_event != nullptr)
    {
        ::SetEvent(g_patch_stop_event);
    }
}

void close_patch_stop_event() noexcept
{
    if (g_patch_stop_event != nullptr)
    {
        ::CloseHandle(g_patch_stop_event);
        g_patch_stop_event = nullptr;
    }
}

bool load_original_module(HMODULE module) noexcept
{
{{LOAD_ORIGIN_MODULE}}
}

ForwarderAddress get_address(PCSTR proc_name) noexcept
{
    OrdinalBuffer ordinal_name{};
    MessageBuffer message{};
    const auto address = ::GetProcAddress(g_origin_module_handle, proc_name);
    if (address != nullptr)
    {
        return address;
    }

    const char* display_name = proc_name;
    if (HIWORD(proc_name) == 0)
    {
        ::StringCchPrintfA(ordinal_name.data(), ordinal_name.size(), "#%u", LOWORD(proc_name));
        display_name = ordinal_name.data();
    }

    ::StringCchPrintf(
        message.data(),
        message.size(),
        TEXT("Cannot locate export %hs."),
        display_name);
    show_message_box(message.data());
    ::ExitProcess(0);
    return nullptr;
}

void init_forwarders() noexcept
{
{{INIT_FORWARDERS}}
}

DWORD WINAPI patch_thread_proc([[maybe_unused]] LPVOID context)
{
    return aheadlibex::user::on_worker_thread() ? 0 : 1;
}

class ScopedHandle final
{
public:
    explicit ScopedHandle(HANDLE handle) noexcept : handle_(handle) {}

    ~ScopedHandle()
    {
        if (handle_ != nullptr)
        {
            ::CloseHandle(handle_);
        }
    }

    ScopedHandle(const ScopedHandle&) = delete;
    ScopedHandle& operator=(const ScopedHandle&) = delete;

private:
    HANDLE handle_;
};

bool launch_patch_thread() noexcept
{
    const auto thread = ::CreateThread(nullptr, 0, patch_thread_proc, nullptr, 0, nullptr);
    if (thread == nullptr)
    {
        show_last_error(TEXT("CreateThread failed"));
        return false;
    }

    ScopedHandle scoped_thread(thread);
    return true;
}

bool start_user_patch() noexcept
{
    const auto lifecycle = aheadlibex::user::configure_patch();
    g_user_patch_started = false;

    if (lifecycle.run_on_process_attach)
    {
        if (!aheadlibex::user::on_process_attach())
        {
            return false;
        }
        g_user_patch_started = true;
    }

    if (lifecycle.create_worker_thread)
    {
        if (!launch_patch_thread())
        {
            return false;
        }
        g_user_patch_started = true;
    }

    return true;
}

} // namespace aheadlibex

BOOL APIENTRY DllMain(HMODULE module, DWORD reason, [[maybe_unused]] PVOID reserved)
{
    switch (reason)
    {
    case DLL_PROCESS_ATTACH:
        aheadlibex::g_proxy_module_handle = module;
        ::DisableThreadLibraryCalls(module);
        if (!aheadlibex::load_original_module(module))
        {
            return FALSE;
        }
        aheadlibex::init_forwarders();
        if (!aheadlibex::create_patch_stop_event() || !aheadlibex::start_user_patch())
        {
            aheadlibex::close_patch_stop_event();
            aheadlibex::free_origin_module();
            return FALSE;
        }
        break;
    case DLL_PROCESS_DETACH:
        aheadlibex::signal_patch_stop();
        if (aheadlibex::g_user_patch_started)
        {
            aheadlibex::user::on_process_detach(reserved != nullptr);
        }
        aheadlibex::close_patch_stop_event();
        aheadlibex::free_origin_module();
        break;
    default:
        break;
    }

    return TRUE;
}
