// generated by AheadLibEx (Rust) - user patch entry

#include "{{PATCH_HEADER}}"

namespace aheadlibex::user {

patch_lifecycle configure_patch() noexcept
{
    patch_lifecycle lifecycle{};
    lifecycle.run_on_process_attach = false;
    lifecycle.create_worker_thread = true;
    return lifecycle;
}

bool on_process_attach() noexcept
{
    // This hook runs directly inside DllMain on DLL_PROCESS_ATTACH.
    // The proxy DLL has finished loading the original DLL and resolved its exports.
    const auto proxy = aheadlibex::proxy_module();
    const auto original = aheadlibex::original_module();
    const auto stop = aheadlibex::stop_event();

    (void)proxy;
    (void)original;
    (void)stop;

    ::OutputDebugString(
        TEXT("AheadLibEx process-attach example ran. Replace this with your loader-lock-safe setup."));

    // TODO: Set configure_patch().run_on_process_attach = true
    // when setup must begin inside DllMain.
    // Keep this path short and loader-lock-safe.
    return true;
}

bool on_worker_thread() noexcept
{
    // This hook runs on the worker thread created by AheadLibEx.
    const auto proxy = aheadlibex::proxy_module();
    const auto original = aheadlibex::original_module();
    const auto stop = aheadlibex::stop_event();

    (void)proxy;
    (void)original;

    if (stop == nullptr)
    {
        return false;
    }

    ::MessageBox(
        nullptr,
        TEXT("AheadLibEx worker thread example is running.\nReplace this MessageBox with your own patch logic."),
        TEXT("AheadLibEx"),
        MB_OK | MB_ICONINFORMATION);

    // TODO: Leave configure_patch().create_worker_thread = true
    // for long-running or blocking work outside DllMain.
    // Example: wait on the stop event so the thread can exit cleanly.
    while (::WaitForSingleObject(stop, 1000) == WAIT_TIMEOUT)
    {
        ::OutputDebugString(
            TEXT("AheadLibEx worker thread example tick. Replace this with your recurring patch work."));

        // TODO: Put recurring patch work here.
        // if (aheadlibex::stop_requested()) { break; }
    }

    ::OutputDebugString(TEXT("AheadLibEx worker thread example received stop_event and is exiting."));
    return true;
}

void on_process_detach(bool process_terminating) noexcept
{
    if (aheadlibex::stop_requested())
    {
        ::OutputDebugString(
            TEXT("AheadLibEx detach example saw stop_event already signaled. Stop your patch here."));
    }

    if (process_terminating)
    {
        ::OutputDebugString(
            TEXT("AheadLibEx detach example is running during process termination. Keep cleanup minimal."));
    }
    else
    {
        ::OutputDebugString(
            TEXT("AheadLibEx detach example cleanup ran. Release lightweight patch resources here."));
    }

    // TODO: Release lightweight resources here.
    // Keep this path short: DLL_PROCESS_DETACH still runs under DllMain.
}

} // namespace aheadlibex::user
